version: '3.8'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "taskflow-db"
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
